apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paylibero-db-mysql
  labels:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: '8.2'
    helm.sh/chart: 'mysql-9.14.3'
spec:
  replicas: 1
  podManagementPolicy: ''
  selector:
    matchLabels:
      app.kubernetes.io/instance: paylibero-db
      app.kubernetes.io/name: mysql
  serviceName: paylibero-db-mysql
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: paylibero-db
        app.kubernetes.io/name: mysql
        app.kubernetes.io/version: '8.2'
        helm.sh/chart: 'mysql-9.14.3'
    spec:
      serviceAccountName: paylibero-db-mysql
      affinity:
        podAffinity: null
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: paylibero-db
                    app.kubernetes.io/name: mysql
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity: null
      securityContext:
        fsGroup: 1001
      #initContainers: null
      containers:
        - name: mysql
          image: hub.hamdocker.ir/bitnami/mysql:8.2
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: BITNAMI_DEBUG
              value: 'false'
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: password
            - name: MYSQL_DATABASE
              value: laravel
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 25
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -c
                - 'mysqladmin status -uroot -p${MYSQL_ROOT_PASSWORD}'
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 25
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -c
                - 'mysqladmin status -uroot -p${MYSQL_ROOT_PASSWORD}'
          volumeMounts:
            - name: data
              mountPath: /bitnami/mysql
            - name: config
              mountPath: /opt/bitnami/mysql/conf/my.cnf
              subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: paylibero-db-mysql
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/instance: paylibero-db
          app.kubernetes.io/name: mysql
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paylibero-db-mysql
  labels:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/name: mysql
