"/health":
  get:
    tags:
      - global
    summary: "Check system health"
    description: "Performs a series of checks to ensure the system is functioning correctly."
    operationId: healthCheck
    responses:
      "200":
        description: "Successful response"
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: success
                code:
                  type: integer
                  example: 200
                message:
                  type: string
                  example: "System health check passed successfully."
                data:
                  type: object
                  properties:
                    overall_status:
                      type: string
                      example: ok
                    checks:
                      type: object
                      properties:
                        database:
                          type: string
                          example: ok
                        redis:
                          type: string
                          example: ok
                        cache:
                          type: string
                          example: ok
                        queue:
                          type: string
                          example: ok

"/daily-rate-range":
  get:
    tags:
      - global
    summary: "Get daily rate range"
    description: ""
    operationId: getDailyRateRange
    responses:
      "200":
        description: "Successful response"
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: success
                code:
                  type: integer
                  example: 200
                message:
                  type: string
                  example: "The daily rate range was retrieved successfully."
                data:
                  type: object
                  properties:
                    min:
                      type: integer
                      example: 56763
                    max:
                      type: integer
                      example: 69377
                    rate:
                      type: integer
                      example: 72070

"/temp":
  get:
    tags:
      - global
    summary: "Temp"
    description: "Temp"
    operationId: healthTemp
    responses:
      "200":
        description: "Successful response"
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: success
                code:
                  type: integer
                  example: 200
                message:
                  type: string
                  example: "System health check passed successfully."
                data:
                  type: object
                  properties:
                    overall_status:
                      type: string
                      example: ok
                    checks:
                      type: object
                      properties:
                        database:
                          type: string
                          example: ok
                        redis:
                          type: string
                          example: ok
                        cache:
                          type: string
                          example: ok
                        queue:
                          type: string
                          example: ok
