apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-worker
  namespace: paylibero-nightly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-worker
  template:
    metadata:
      labels:
        app: queue-worker
        commit-short-sha: commit_5d9ba9b7
    spec:
      containers:
      - args:
        - artisan
        - queue:work
        - --tries=3
        - --backoff=5
        command:
        - php
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: core-laravel-mysql-db
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: core-laravel-mysql-db
        - name: REDIS_HOST
          value: redis-headless
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis
        envFrom:
          env:
          - name: APP_NAME
            value: Laravel
          - name: APP_ENV
            value: production
          - name: DB_PORT
            value: "3306"
          - name: APP_KEY
            value: ggrz5rUpSYczpc
          - name: APP_DEBUG
            value: "false"
          - name: APP_URL
            value: https://core-lara-33e1254e7d-paylibero-nightly.apps.ir-thr-ba1.arvancaas.ir
          - name: LOG_CHANNEL
            value: stack
          - name: LOG_DEPRECATIONS_CHANNEL
            value: "null"
          - name: LOG_LEVEL
            value: debug
          - name: DB_CONNECTION
            value: mysql
          - name: DB_HOST
            value: paylibero-db-mysql-headless
          - name: DB_DATABASE
            value: laravel
          - name: MYSQL_DATABASE
            value: laravel
          - name: BROADCAST_DRIVER
            value: log
          - name: CACHE_DRIVER
            value: file
          - name: FILESYSTEM_DISK
            value: local
          - name: QUEUE_CONNECTION
            value: sync
          - name: SESSION_DRIVER
            value: file
          - name: SESSION_LIFETIME
            value: "120"
          - name: MEMCACHED_HOST
            value: 127.0.0.1
          - name: REDIS_PORT
            value: "6379"
          - name: RUN_SETUP_COMMANDS
            value: "false"
        image: registry.hamdocker.ir/paylibero/queue-worker:5d9ba9b7
        name: queue-worker
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: 128m
            memory: 256Mi
          requests:
            cpu: 64m
            memory: 128Mi
      imagePullSecrets:
      - name: hamdocker
      restartPolicy: Always