apiVersion: v1
kind: Service
metadata:
  name: paylibero-db-mysql-headless
  labels:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: "8.2"
    helm.sh/chart: "mysql-9.14.3"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: paylibero-db-mysql
  labels:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: "8.2"
    helm.sh/chart: "mysql-9.14.3"
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
      nodePort: null
  selector:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/name: mysql
