apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-laravel
spec:
  template:
    spec:
      initContainers:
        - name: laravel-setup
          env:
            # APP--------------------------------------
            - name: APP_ENV
              value: staging
            - name: APP_URL
              value: https://staging.paylibero.ir
            - name: USER_DASHBOARD_URL
              value: https://staging.paylibero.ir/dashboard

            # DB--------------------------------------
            - name: DB_HOST
              value: paylibero-db-mysql-headless
            - name: DB_PORT
              value: '3306'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: password

            # RECAPTCHA--------------------------------------
            - name: RECAPTCHA_V3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: secret_key
            - name: RECAPTCHA_V3_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: site_key
            - name: RECAPTCHA_V3_ENABLE
              value: 'false'

            # REDIS--------------------------------------
            - name: REDIS_LEADER_HOST
              value: redis-cluster-leader.paylibero-staging.svc.cluster.local
            - name: REDIS_LEADER_ADDITIONAL_HOST
              value: redis-cluster-leader-additional.paylibero-staging.svc.cluster.local
            - name: REDIS_FOLLOWER_HOST
              value: redis-cluster-follower.paylibero-staging.svc.cluster.local
            - name: REDIS_FOLLOWER_ADDITIONAL_HOST
              value: redis-cluster-follower-additional.paylibero-staging.svc.cluster.local
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password

            # MAIL--------------------------------------
            - name: MAIL_USERNAME
              value: '10cSOoYX8R'
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ahasend
                  key: password

            # ZIBAL_CALLBACK_URL--------------------------------------
            - name: ZIBAL_CALLBACK_URL
              value: https://staging.paylibero.ir/api/gateway/callback

            # FINNOTECH--------------------------------------
            - name: FINNOTECH_BASE_URL
              value: https://sandboxapi.finnotech.ir
            - name: FINNOTECH_CLIENT_ID
              value: paylibero
            - name: FINNOTECH_CLIENT_CREDENTIALS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: client-credentials-token
            - name: FINNOTECH_AUTHORIZATION_CODE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: authorization-code-token
            - name: FRONTEND_URL_AFTER_PAYMENT
              value: https://nightly.paylibero.ir/dashboard/trades
            - name: FINNOTECH_AUTHORIZATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: authorization-token
            # SANCTUM--------------------------------------
            - name: SANCTUM_STATEFUL_DOMAINS
              value: staging.paylibero.ir,admin.staging.paylibero.ir,staging.paylibero.de,admin.staging.paylibero.de,staging.paylibero.net,admin.staging.paylibero.net
            - name: SESSION_DOMAIN
              value: staging.paylibero.ir

            # AWS--------------------------------------
            - name: AWS_URL
              value: https://files-staging.paylibero.ir/
            - name: AWS_DEFAULT_REGION
              value: Simin
            - name: AWS_BUCKET
              value: paylibero-staging-core
            - name: FILESYSTEM_DISK
              value: s3
            - name: AWS_USE_PATH_STYLE_ENDPOINT
              value: 'false'
            - name: AWS_ENDPOINT
              value: https://s3.ir-thr-at1.arvanstorage.ir
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: file-storage
                  key: id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: file-storage
                  key: access-key

      containers:
        - name: core-laravel
          resources:
            limits:
              cpu: '1'
              ephemeral-storage: 200M
              memory: 2G
            requests:
              cpu: '1'
              ephemeral-storage: 200M
              memory: 2G

          env:
            # APP--------------------------------------
            - name: APP_ENV
              value: staging
            - name: APP_URL
              value: https://staging.paylibero.ir
            - name: USER_DASHBOARD_URL
              value: https://staging.paylibero.ir/dashboard

            # DB--------------------------------------
            - name: DB_HOST
              value: paylibero-db-mysql-headless
            - name: DB_PORT
              value: '3306'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: password

            # RECAPTCHA--------------------------------------
            - name: RECAPTCHA_V3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: secret_key
            - name: RECAPTCHA_V3_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: site_key
            - name: RECAPTCHA_V3_ENABLE
              value: 'false'

            # REDIS--------------------------------------
            - name: REDIS_HOST
              value: redis-cluster-leader-headless
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password

            # MAIL--------------------------------------
            - name: MAIL_USERNAME
              value: '10cSOoYX8R'
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ahasend
                  key: password

            # ZIBAL_CALLBACK_URL--------------------------------------
            - name: ZIBAL_CALLBACK_URL
              value: https://staging.paylibero.ir/api/gateway/callback

            # FINNOTECH--------------------------------------
            - name: FINNOTECH_BASE_URL
              value: https://sandboxapi.finnotech.ir
            - name: FINNOTECH_CLIENT_ID
              value: paylibero
            - name: FINNOTECH_CLIENT_CREDENTIALS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: client-credentials-token
            - name: FINNOTECH_AUTHORIZATION_CODE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: authorization-code-token
            - name: FRONTEND_URL_AFTER_PAYMENT
              value: https://nightly.paylibero.ir/dashboard/trades
            - name: FINNOTECH_AUTHORIZATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: authorization-token
            # SANCTUM--------------------------------------
            - name: SANCTUM_STATEFUL_DOMAINS
              value: staging.paylibero.ir,admin.staging.paylibero.ir,staging.paylibero.de,admin.staging.paylibero.de,staging.paylibero.net,admin.staging.paylibero.net
            - name: SESSION_DOMAIN
              value: staging.paylibero.ir

            # AWS--------------------------------------
            - name: AWS_URL
              value: https://files-staging.paylibero.ir/
            - name: AWS_DEFAULT_REGION
              value: Simin
            - name: AWS_BUCKET
              value: paylibero-staging-core
            - name: FILESYSTEM_DISK
              value: s3
            - name: AWS_USE_PATH_STYLE_ENDPOINT
              value: 'false'
            - name: AWS_ENDPOINT
              value: https://s3.ir-thr-at1.arvanstorage.ir
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: file-storage
                  key: id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: file-storage
                  key: access-key
