apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-laravel
spec:
  template:
    spec:
      initContainers:
        - name: laravel-setup
          env:
            # APP--------------------------------------
            - name: APP_ENV
              value: production
            - name: APP_URL
              value: https://paylibero.ir
            - name: USER_DASHBOARD_URL
              value: https://paylibero.ir/dashboard

            # DB--------------------------------------
            - name: DB_HOST
              value: 843fbabc874f4aadbfaff523cb194058.db.arvandbaas.ir
            - name: DB_PORT
              value: '3306'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: password

            # RECAPTCHA--------------------------------------
            - name: RECAPTCHA_V3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: secret_key
            - name: RECAPTCHA_V3_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: site_key
            - name: RECAPTCHA_V3_ENABLE
              value: 'false'

            # REDIS--------------------------------------
            - name: REDIS_CLIENT
              value: phpredis
            - name: REDIS_CLUSTER
              value: redis
            - name: REDIS_HOST
              value: redis-standalone
            # - name: REDIS_LEADER_HOST
            #   value: redis-cluster-leader
            # - name: REDIS_LEADER_ADDITIONAL_HOST
            #   value: redis-cluster-leader-additional
            # - name: REDIS_FOLLOWER_HOST
            #   value: redis-cluster-follower
            # - name: REDIS_FOLLOWER_ADDITIONAL_HOST
            #   value: redis-cluster-follower-additional
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password

            # MAIL--------------------------------------
            - name: MAIL_USERNAME
              value: '10cSOoYX8R'
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ahasend
                  key: password

            # ZIBAL_CALLBACK_URL--------------------------------------
            - name: ZIBAL_CALLBACK_URL
              value: https://paylibero.ir/api/gateway/callback

            # FINNOTECH--------------------------------------
            - name: FINNOTECH_BASE_URL
              value: https://sandboxapi.finnotech.ir
            - name: FINNOTECH_CLIENT_ID
              value: paylibero
            - name: FRONTEND_URL_AFTER_PAYMENT
              value: https://paylibero.ir/dashboard/trades
            - name: FINNOTECH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: client-secret
            - name: FINNOTECH_NATIONAL_ID
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: national-id
            - name: FINNOTECH_AUTHORIZATION_CODE
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: authorization-code
            - name: FINNOTECH_AUTHORIZATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: authorization-token
            # SANCTUM--------------------------------------
            - name: SANCTUM_STATEFUL_DOMAINS
              value: paylibero.ir,admin.paylibero.ir,paylibero.de,admin.paylibero.de,paylibero.net,admin.paylibero.net

            # AWS--------------------------------------
            - name: AWS_URL
              value: https://files.paylibero.ir/
            - name: AWS_DEFAULT_REGION
              value: Simin
            - name: AWS_BUCKET
              value: paylibero-production-core
            - name: FILESYSTEM_DISK
              value: s3
            - name: AWS_USE_PATH_STYLE_ENDPOINT
              value: 'false'
            - name: AWS_ENDPOINT
              value: https://s3.ir-thr-at1.arvanstorage.ir
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: file-storage
                  key: id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: file-storage
                  key: access-key

      containers:
        - name: core-laravel
          resources:
            limits:
              cpu: '.5'
              ephemeral-storage: 1Gi
              memory: 1Gi
            requests:
              cpu: '.5'
              ephemeral-storage: 1Gi
              memory: 1Gi

          env:
            # APP--------------------------------------
            - name: APP_ENV
              value: production
            - name: APP_URL
              value: https://paylibero.ir
            - name: USER_DASHBOARD_URL
              value: https://paylibero.ir/dashboard

            # DB--------------------------------------
            - name: DB_HOST
              value: 843fbabc874f4aadbfaff523cb194058.db.arvandbaas.ir
            - name: DB_PORT
              value: '3306'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: password

            # RECAPTCHA--------------------------------------
            - name: RECAPTCHA_V3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: secret_key
            - name: RECAPTCHA_V3_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: site_key
            - name: RECAPTCHA_V3_ENABLE
              value: 'false'

            # REDIS--------------------------------------
            - name: REDIS_CLIENT
              value: phpredis
            - name: REDIS_CLUSTER
              value: redis
            - name: REDIS_HOST
              value: redis-standalone
            # - name: REDIS_LEADER_HOST
            #   value: redis-cluster-leader
            # - name: REDIS_LEADER_ADDITIONAL_HOST
            #   value: redis-cluster-leader-additional
            # - name: REDIS_FOLLOWER_HOST
            #   value: redis-cluster-follower
            # - name: REDIS_FOLLOWER_ADDITIONAL_HOST
            #   value: redis-cluster-follower-additional
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password

            # MAIL--------------------------------------
            - name: MAIL_USERNAME
              value: '10cSOoYX8R'
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ahasend
                  key: password

            # ZIBAL_CALLBACK_URL--------------------------------------
            - name: ZIBAL_CALLBACK_URL
              value: https://paylibero.ir/api/gateway/callback

            # FINNOTECH--------------------------------------
            - name: FINNOTECH_BASE_URL
              value: https://sandboxapi.finnotech.ir
            - name: FINNOTECH_CLIENT_ID
              value: paylibero
            - name: FRONTEND_URL_AFTER_PAYMENT
              value: https://paylibero.ir/dashboard/trades
            - name: FINNOTECH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: client-secret
            - name: FINNOTECH_NATIONAL_ID
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: national-id
            - name: FINNOTECH_AUTHORIZATION_CODE
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: authorization-code
            - name: FINNOTECH_AUTHORIZATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: authorization-token
            # SANCTUM--------------------------------------
            - name: SANCTUM_STATEFUL_DOMAINS
              value: paylibero.ir,admin.paylibero.ir,paylibero.de,admin.paylibero.de,paylibero.net,admin.paylibero.net
            # AWS--------------------------------------
            - name: AWS_URL
              value: https://files.paylibero.ir/
            - name: AWS_DEFAULT_REGION
              value: Simin
            - name: AWS_BUCKET
              value: paylibero-production-core
            - name: FILESYSTEM_DISK
              value: s3
            - name: AWS_USE_PATH_STYLE_ENDPOINT
              value: 'false'
            - name: AWS_ENDPOINT
              value: https://s3.ir-thr-at1.arvanstorage.ir
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: file-storage
                  key: id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: file-storage
                  key: access-key
