apiVersion: v1
kind: ServiceAccount
metadata:
  name: paylibero-db-mysql
  labels:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 8.0.35
    helm.sh/chart: mysql-9.14.3
automountServiceAccountToken: true
secrets:
  - name: paylibero-db-mysql
