include: /.gitlab-ci.templates.yml

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_ID && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "production")'
    - if: '$CI_MERGE_REQUEST_ID == null && $CI_COMMIT_REF_NAME == "main"'
    - if: '$CI_MERGE_REQUEST_ID == null && $CI_COMMIT_REF_NAME == "production"'

stages:
  - Composer
  - Test
  - Build
  - Deploy

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

composer:
  stage: Composer
  image: lorisleiva/laravel-docker:8.2
  script:
    - cd lara-app
    - php -v
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
  artifacts:
    paths:
      - lara-app/vendor/
      - lara-app/.env
    expire_in: 1 days
    when: always
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - lara-app/vendor/

phpunit:
  stage: Test
  image: lorisleiva/laravel-docker:8.2
  dependencies:
    - composer
  script:
    - cd lara-app
    - cat .env
    - php -v
    - php artisan migrate:fresh --seed
    - php -d memory_limit=256M ./vendor/bin/phpunit --coverage-text --colors=never
  services:
    - name: mysql:8.2
      command: ["--default-authentication-plugin=mysql_native_password"]
  variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: laravel
    DB_HOST: mysql
    DB_CONNECTION: mysql
    DB_PORT: 3306
    MYSQL_USER: paylibero
    MYSQL_PASSWORD: Col18light
  artifacts:
    paths:
      - lara-app/storage/logs
    expire_in: 1 days
    when: on_failure

build-nightly:
  stage: Build
  extends: .build_job_template
  variables:
    SERVICE_NAME: core-laravel
    ENVIRONMENT_NAME: nightly
  rules:
    - if: '$CI_MERGE_REQUEST_ID == null && $CI_COMMIT_REF_NAME == "main"'
  environment:
    name: $SERVICE_NAME-nightly
    deployment_tier: staging
    action: prepare

deploy-nightly:
  stage: Deploy
  extends: .deploy_job_template
  variables:
    SERVICE_NAME: core-laravel
    ENVIRONMENT_NAME: nightly
    KUBE_CONFIG_NAME: $ARVAN_KUBE_CONFIG_NIGHTLY
  rules:
    - if: '$CI_MERGE_REQUEST_ID == null && $CI_COMMIT_REF_NAME == "main"'
  environment:
    name: $SERVICE_NAME-nightly
    deployment_tier: staging