# image: edbizarro/gitlab-ci-pipeline-php:7.3

stages:
  # - Prepare
  # - Test
  # - Security
  - Build
  - Deploy

# variables:
#   MYSQL_ROOT_PASSWORD: root
#   MYSQL_USER: paylibero
#   MYSQL_PASSWORD: paylibero_secret
#   MYSQL_DATABASE: laravel
#   DB_HOST: mysql

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

# composer:
#   stage: Prepare
#   script:
#     - php -v
#     - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
#     - cp .env.example .env
#     - php artisan key:generate
#   artifacts:
#     paths:
#       - vendor/
#       - .env
#     expire_in: 1 days
#     when: always
#   cache:
#     paths:
#       - vendor/

# db-seeding:
#   stage: Build
#   services:
#     - name: mysql:8.2
#       command: ["--default-authentication-plugin=mysql_native_password"]
#   # Download the artifacts for these jobs
#   dependencies:
#     - composer
#   script:
#     - mysql --version
#     - php artisan migrate:fresh --seed
#     - mysqldump --host="${DB_HOST}" --user="${MYSQL_USER}" --password="${MYSQL_PASSWORD}" "${MYSQL_DATABASE}" > db.sql
#   artifacts:
#     paths:
#       - storage/logs # for debugging
#       - db.sql
#     expire_in: 1 days
#     when: always

# phpunit:
#   stage: Test
#   services:
#     - name: mysql:8.0
#       command: ["--default-authentication-plugin=mysql_native_password"]
#   # Download the artifacts for these jobs
#   dependencies:
#     - build-assets
#     - composer
#     - db-seeding
#   script:
#     - php -v
#     - sudo cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.bak
#     - echo "" | sudo tee /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#     - mysql --host="${DB_HOST}" --user="${MYSQL_USER}" --password="${MYSQL_PASSWORD}" "${MYSQL_DATABASE}" < db.sql
#     - ./vendor/phpunit/phpunit/phpunit --version
#     - php -d short_open_tag=off ./vendor/phpunit/phpunit/phpunit -v --colors=never --stderr
#     - sudo cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.bak /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#   artifacts:
#     paths:
#       - ./storage/logs # for debugging
#     expire_in: 1 days
#     when: on_failure

# codestyle:
#   stage: Test
#   image: lorisleiva/laravel-docker
#   script:
#     - phpcs --extensions=php app
#   dependencies: []

# phpcpd:
#   stage: Test
#   script:
#     - test -f phpcpd.phar || curl -L https://phar.phpunit.de/phpcpd.phar -o phpcpd.phar
#     - php phpcpd.phar app/ --min-lines=50
#   dependencies: []
#   cache:
#     paths:
#       - phpcpd.phar

# sensiolabs:
#   stage: Security
#   script:
#     - test -d security-checker || git clone https://github.com/sensiolabs/security-checker.git
#     - cd security-checker
#     - composer install
#     - php security-checker security:check ../composer.lock
#   dependencies: []
#   cache:
#     paths:
#       - security-checker/

build-nightly:
  stage: Build
  extends: .build_job_template
  variables:
    SERVICE_NAME: core-laravel
    ENVIRONMENT_NAME: nightly
  # rules:
  #   - if: '$CI_MERGE_REQUEST_ID == null && $CI_COMMIT_REF_NAME == "main"'
  environment:
    name: $SERVICE_NAME-nightly
    deployment_tier: staging
    action: prepare

deploy-nightly:
  stage: Deploy
  extends: .deploy_job_template
  variables:
    SERVICE_NAME: core-laravel
    ENVIRONMENT_NAME: nightly
  # rules:
  #   - if: '$CI_MERGE_REQUEST_ID == null && $CI_COMMIT_REF_NAME == "main"'
  environment:
    name: $SERVICE_NAME-nightly
    deployment_tier: staging
