apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-laravel
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 75%
  template:
    metadata:
      labels:
        app: core-laravel
        commit-short-sha: "commit_${DEPLOY_COMMIT_SHORT_SHA}"
    spec:
      restartPolicy: Always
      imagePullSecrets:
       - name: hamdocker
      initContainers:
        - name: laravel-setup
          image: registry.hamdocker.ir/paylibero/build-core-laravel
          volumeMounts:
            - mountPath: /var/www/storage
              name: storage-volume
          command: ["/bin/sh", "-c"]
          args:
            - |
              cd /var/www
              php artisan optimize:clear
              php artisan optimize
              php artisan migrate --force
          envFrom:
            - configMapRef:
                name: core-laravel
          env:
            - name: HOSTNAME
              value: php
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: core-laravel-storage-pvc
      containers:
        - image: registry.hamdocker.ir/paylibero/build-core-laravel
          imagePullPolicy: Always
          name: core-laravel
          volumeMounts:
            - mountPath: /var/www/storage
              name: storage-volume
          ports:
            - containerPort: 8000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 60
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 1
          envFrom:
            - configMapRef:
                name: core-laravel
          env:
            - name: HOSTNAME
              value: php
          resources: {}