apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-laravel
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 75%
  template:
    metadata:
      labels:
        app: core-laravel
        commit-short-sha: "commit_${DEPLOY_COMMIT_SHORT_SHA}"
    spec:
      restartPolicy: Always
      imagePullSecrets:
       - name: hamdocker
      initContainers:
        - name: laravel-setup
          env:
            - name: APP_NAME
              value: Laravel
            - name: APP_ENV
              value: production
            - name: DB_PORT
              value: '3306'
            - name: APP_KEY
              value: "base64:yQhAdFdboNEdYLvoysezy0/gyKxDdwJM9SsqdtCzNhw="
            - name: APP_DEBUG
              value: 'false'
            - name: APP_URL
              value: https://core-lara-33e1254e7d-paylibero-nightly.apps.ir-thr-ba1.arvancaas.ir
            - name: LOG_CHANNEL
              value: stack
            - name: LOG_DEPRECATIONS_CHANNEL
              value: 'null'
            - name:  LOG_LEVEL 
              value: debug
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: paylibero-db-mysql-headless
            - name: DB_DATABASE
              value: laravel
            - name: DB_USERNAME
              value: paylibero
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paylibero-db-mysql
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: laravel
            - name: BROADCAST_DRIVER
              value: log
            - name: CACHE_DRIVER
              value: file
            - name: FILESYSTEM_DISK
              value: local
            - name: QUEUE_CONNECTION
              value: sync
            - name: SESSION_DRIVER
              value: file
            - name: SESSION_LIFETIME
              value: '120'
            - name: MEMCACHED_HOST
              value: '127.0.0.1'
            
            - name: SENTRY_LARAVEL_DSN
              value: https://2e6c8a38ddf48ff4820e3cd0e466a6e1@sentry.hamravesh.com/6536

            - name: SENTRY_TRACES_SAMPLE_RATE
              value: "1.0"

            - name: REDIS_HOST
              value: redis-headless
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: REDIS_PORT
              value: '6379'

            - name: RUN_SETUP_COMMANDS
              value: 'false'
          image: registry.hamdocker.ir/paylibero/build-core-laravel
          command: ["/bin/sh", "-c"]
          args:
            - |
              cd /var/www
              php artisan optimize:clear
              php artisan optimize
              php artisan migrate --force
      containers:
        - image: registry.hamdocker.ir/paylibero/build-core-laravel
          imagePullPolicy: Always
          name: core-laravel
          ports:
            - containerPort: 8000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 60
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: APP_NAME
              value: Laravel
            - name: APP_ENV
              value: production
            - name: DB_PORT
              value: '3306'
            - name: APP_KEY
              value: "base64:yQhAdFdboNEdYLvoysezy0/gyKxDdwJM9SsqdtCzNhw="
            - name: APP_DEBUG
              value: 'false'
            - name: APP_URL
              value: https://core-lara-33e1254e7d-paylibero-nightly.apps.ir-thr-ba1.arvancaas.ir
            - name: LOG_CHANNEL
              value: stack
            - name: LOG_DEPRECATIONS_CHANNEL
              value: 'null'
            - name:  LOG_LEVEL 
              value: debug
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: paylibero-db-mysql-headless
            - name: DB_DATABASE
              value: laravel
            - name: MYSQL_DATABASE
              value: laravel
            - name: BROADCAST_DRIVER
              value: log
            - name: CACHE_DRIVER
              value: file
            - name: FILESYSTEM_DISK
              value: local
            - name: QUEUE_CONNECTION
              value: sync
            - name: SESSION_DRIVER
              value: file
            - name: SESSION_LIFETIME
              value: '120'
            - name: MEMCACHED_HOST
              value: '127.0.0.1'

            - name: REDIS_HOST
              value: redis-headless
            
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: REDIS_PORT
              value: '6379'

            - name: RUN_SETUP_COMMANDS
              value: 'false'
          resources: {}