apiVersion: apps/v1
kind: Deployment
metadata:
  name: pex-storybook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pex-storybook
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 75%
  template:
    metadata:
      labels:
        app: pex-storybook
        commit-short-sha: "commit_${DEPLOY_COMMIT_SHORT_SHA}"
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: hamdocker
      containers:
        - image: registry.hamdocker.ir/paylibero/pex-storybook
          imagePullPolicy: Always
          name: pex-storybook
          resources: {}

          ports:
            - containerPort: 80

          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1

          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1