apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-worker
  template:
    metadata:
      labels:
        app: queue-worker
        commit-short-sha: "commit_${DEPLOY_COMMIT_SHORT_SHA}"
    spec:
      restartPolicy: Always
      imagePullSecrets:
       - name: hamdocker
      volumes:
        - name: worker-logs
          emptyDir: {}
      containers:
        - image: registry.hamdocker.ir/paylibero/queue-worker
          name: queue-worker
          volumeMounts:
            - name: worker-logs
              mountPath: /var/log/supervisor
          ports:
            - containerPort: 8000
              protocol: TCP
          resources: {}
          env:
            - name: REDIS_PORT
              value: '6379'
