apiVersion: v1
kind: ServiceAccount
metadata:
  name: paylibero-db-mysql
  namespace: paylibero-production
  labels:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 8.0.35
    helm.sh/chart: mysql-9.14.3
automountServiceAccountToken: true
secrets:
  - name: paylibero-db-mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: paylibero-db-mysql
  namespace: paylibero-production
  labels:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 8.0.35
    helm.sh/chart: mysql-9.14.3
type: Opaque
data:
  mysql-root-password: Q29sMThuaWdodA==
  mysql-password: Q29sMThuaWdodA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paylibero-db-mysql
  namespace: paylibero-production
  labels:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 8.0.35
    helm.sh/chart: mysql-9.14.3
    app.kubernetes.io/component: primary
data:
  my.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    slow_query_log=0
    long_query_time=10.0

    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
---
apiVersion: v1
kind: Service
metadata:
  name: paylibero-db-mysql-headless
  namespace: paylibero-production
  labels:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 8.0.35
    helm.sh/chart: mysql-9.14.3
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: primary
---
apiVersion: v1
kind: Service
metadata:
  name: paylibero-db-mysql
  namespace: paylibero-production
  labels:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 8.0.35
    helm.sh/chart: mysql-9.14.3
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
      nodePort: null
  selector:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: primary
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paylibero-db-mysql
  namespace: paylibero-production
  labels:
    app.kubernetes.io/instance: paylibero-db
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 8.0.35
    helm.sh/chart: mysql-9.14.3
    app.kubernetes.io/component: primary
spec:
  replicas: 1
  podManagementPolicy: ""
  selector:
    matchLabels:
      app.kubernetes.io/instance: paylibero-db
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: primary
  serviceName: paylibero-db-mysql
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configuration: 9ebd07b18aa64a6cace43b82215c042248d5c64d0858f4fc57e94e45dfeb136b
      labels:
        app.kubernetes.io/instance: paylibero-db
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mysql
        app.kubernetes.io/version: 8.0.35
        helm.sh/chart: mysql-9.14.3
        app.kubernetes.io/component: primary
    spec:
      serviceAccountName: paylibero-db-mysql
      affinity:
        podAffinity: null
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: paylibero-db
                    app.kubernetes.io/name: mysql
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity: null
      securityContext:
        fsGroup: 1001
      initContainers: null
      containers:
        - name: mysql
          image: docker.io/bitnami/mysql:8.2
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paylibero-db-mysql
                  key: mysql-root-password
            - name: MYSQL_USER
              value: paylibero
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paylibero-db-mysql
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: laravel
          envFrom: null
          ports:
            - name: mysql
              containerPort: 3306
          resources:
            limits:
              cpu: ".5"
              memory: 1G
            requests:
              cpu: ".5"
              memory: 1G
          volumeMounts:
            - name: data
              mountPath: /bitnami/mysql
            - name: config
              mountPath: /opt/bitnami/mysql/conf/my.cnf
              subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: paylibero-db-mysql
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/instance: paylibero-db
          app.kubernetes.io/name: mysql
          app.kubernetes.io/component: primary
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
