apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paylibero-db-mysql
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: mysql
          resources:
            requests:
              cpu: "0.5"
              memory: 1G
            limits:
              cpu: "0.5"
              memory: 1G
