apiVersion: v1
kind: ConfigMap
metadata:
  name: core-laravel
data:
  APP_DEBUG: "false"
  APP_KEY: "base64:yQhAdFdboNEdYLvoysezy0/gyKxDdwJM9SsqdtCzNhw="
  APP_NAME: Laravel
  APP_URL: https://core-lara-33e1254e7d-paylibero-nightly.apps.ir-thr-ba1.arvancaas.ir
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  DB_CONNECTION: mysql
  DB_DATABASE: laravel
  FILESYSTEM_DISK: local
  LOG_CHANNEL: stack
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: debug
  MEMCACHED_HOST: "127.0.0.1"
  MYSQL_DATABASE: laravel
  QUEUE_CONNECTION: redis
  SENTRY_LARAVEL_DSN: https://2e6c8a38ddf48ff4820e3cd0e466a6e1@sentry.hamravesh.com/6536
  SENTRY_TRACES_SAMPLE_RATE: "1.0"
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "send.ahasend.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "10cSOoYX8R"
  MAIL_ENCRYPTION: "tls"
  MAIL_FROM_ADDRESS: "noreply@paylibero.ir"
  MAIL_FROM_NAME: "Paylibero"
  REDIS_CLIENT: predis
  DEPLOY_MODE: "true"
  ACCESS_TOKEN_EXPIRATION_TIME_PER_MINUTES: "3"
  REFRESH_TOKEN_EXPIRATION_TIME_PER_MINUTES: "14400"
  SANCTUM_STATEFUL_DOMAINS: "localhost:4000,core-lara-33e1254e7d-paylibero-nightly.apps.ir-thr-ba1.arvancaas.ir,nightly.paylibero.ir"
  SESSION_DOMAIN: ".paylibero.ir"
  AWS_ACCESS_KEY_ID: "9df70835-f9fd-425b-ba76-051fc737db6a"
  AWS_SECRET_ACCESS_KEY: "2bbc941c0a3fd868d7e08e2bdd3ce35a91cad8adfcabfa8fd210a7bc5a35977d"
  AWS_URL: "https://files.paylibero.ir/"
  AWS_ENDPOINT: "s3.ir-thr-at1.arvanstorage.ir"
  ZIBAL_CALLBACK_URL: "https://nightly.paylibero.ir/api/gateway/callback"
  FINNOTECH_BASE_URL: "https://sandboxapi.finnotech.ir"
  FINNOTECH_CLIENT_ID: "paylibero"
  FINNOTECH_TOKEN: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbklkIjoiZDQwZWVmZTctNjQzYy00YTQ3LThmODItYzA5MjMyOGE1ZDQyIiwicmVmcmVzaFRva2VuIjoiakZWdXhTSmo1MElCRlYwbEgyOWZnemtqOTQ4d3kzTm94R2NKU1dwNUFvVXpmcDNzTlJxSTZ2RU04M2M2SFk2V2IzSGo5UHVDV1JDQnlzMDRzTmxtblZyOEVBMWYwaGd1NUozQTVzeGMxcGxSN1lWZ2RuYThycnZQdVVyUWYyODlVOEhSVEVFcHF1Vkx4bHRaNW1MZm5DdHZLbEFDY0dGZFkwMDFKVmptUkVHNUNtNVlmNmRFSkhnRVhhVU1KUGZDamx6Nk9mbUVTdWY4VHN1NzN2R3R1djcwYkhwYWd5OEFRWGJuR3RsN1gxVWFmbTJReTRQT2NONVducE5jMmQxYiIsImNyZWF0aW9uRGF0ZSI6IjE0MDMwNjEwMTE1MDExIiwibGlmZVRpbWUiOjg2NDAwMDAwMCwiY2xpZW50SWQiOiJwYXlsaWJlcm8iLCJ1c2VySWQiOiI0Mjg1Nzg3NjUyIiwiYWN0aXZlIjp0cnVlLCJzY29wZXMiOlsiZmFjaWxpdHk6Y2FyZC10by1pYmFuOmdldCJdLCJ0eXBlIjoiQ0xJRU5ULUNSRURFTlRJQUwiLCJjbGllbnRJbmZvIjoid20zNGFMY2dDQitIT2UxZlN1eFNmWmdNWjB0RHc0UzVRVXYxakNNTyIsImJhbmsiOiIwNjIiLCJpYXQiOjE3MjUwODg4MTEsImV4cCI6MTcyNTk1MjgxMX0.pFYJvkj08QBfMXTgsfkSzIpHF3zNQITW82haZmKLNTv5ClVzlzNs2gV5BU6CpAxMbgjPQljAqXtmcPh5Y6r7Z3OyAo2Owm6kxNwBVGC8Wp5c5ZOzHvY9KRf-pD_eoYOcZU8_OWxUDY14TTEyQ56qJmAcJkey-3izSP-tqIPJp-ACp43rTG8K6zI1G4gwuRCZiVGF9mvCRDinHS-jqOiQWElmTgu0M5uyKJdfm8BIgbluYyvO6WYZNgF64VaUDfcZYJtxmh7IDAW5_Hc-l9YVPMpTSVhOWHk4V6I7sB5LgkDUV5qAEFya3REcwh4j0E7XYn9hw8aPiYhyZTukbG025Q"