"/requests":
  get:
    tags:
      - guests
    summary: "Get all system requests"
    description: "Get all requests"
    operationId: getAllRequests
    parameters:
      - $ref: "#/components/parameters/requestType"
      - $ref: "#/components/parameters/requestSort"
      - $ref: "#/components/parameters/pageSize"
      - $ref: "#/components/parameters/pageNumber"
      - $ref: "#/components/parameters/requestStatus"
      - name: filter[payment_method]
        in: query
        description: The type of payment_method
        required: false
        schema:
          type: array
          items:
            type: string
            enum: [foreign_bank, paypal]
          example: [paypal]
      - name: filter[volume_from]
        in: query
        description: The minimum volume range of the requests (0 - 100000)
        required: false
        schema:
          type: integer
          minimum: 0
          maximum: 100000
          example: 150

      - name: filter[volume_to]
        in: query
        description: The maximum volume range of the requests (0 - 100000)
        required: false
        schema:
          type: integer
          minimum: 0
          maximum: 100000
          example: 150

    responses:
      "200":
        description: "The requests was retrieved successfully."
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Base200Response"
                - type: object
                  required:
                    - data
                  properties:
                    data:
                      type: object
                      required:
                        - items
                        - pagination
                      properties:
                        pagination:
                          $ref: "#/components/schemas/Pagination"
                        items:
                          type: array
                          description: "Array of request items"
                          items:
                            $ref: "#/components/schemas/Request"
