"/requests":
  get:
    tags:
      - guests
    summary: "Get all system requests"
    description: "Get all requests"
    operationId: getAllRequests
    parameters:
      - name: filter[type]
        in: query
        description: The type of request
        required: false
        schema:
          type: string
          enum: [buy, sell]
          example: buy
      - name: filter[status]
        in: query
        description: The status of the request
        required: false
        schema:
          type: string
          enum: [pending, processing, trading, canceled]
          example: pending

      - name: filter[volume_from]
        in: query
        description: The minimum volume range of the requests (0 - 100000)
        required: false
        schema:
          type: integer
          minimum: 0
          maximum: 100000
          example: 150

      - name: filter[volume_to]
        in: query
        description: The maximum volume range of the requests (0 - 100000)
        required: false
        schema:
          type: integer
          minimum: 0
          maximum: 100000
          example: 150

      - name: sort
        in: query
        description: The sort order of the results
        required: false
        schema:
          type: string
          enum: [created_at, -created_at, price, -price]
          example: -created_at
      - name: per_page
        in: query
        description: "Number of items to return per page"
        required: false
        schema:
          type: integer
          default: 15
      - name: page
        in: query
        description: "page number"
        required: false
        schema:
          type: integer
          default: 1
    responses:
      "200":
        description: "The requests was retrieved successfully."
        content:
          application/json:
            schema:
              type: object
              required:
                - status
                - code
                - message
                - data
              properties:
                status:
                  type: string
                  description: "The status of the API response"
                  example: "success"
                code:
                  type: integer
                  description: "The HTTP status code of the response"
                  example: 200
                message:
                  type: string
                  description: "A descriptive message about the response"
                  example: "The requests were retrieved successfully."
                data:
                  type: object
                  required:
                    - items
                    - pagination
                  properties:
                    items:
                      type: array
                      description: "Array of request items"
                      items:
                        type: object
                        required:
                          - ulid
                          - number
                          - volume
                          - price
                          - type
                          - status
                          - created_at
                          - updated_at
                          - payment_methods
                        properties:
                          ulid:
                            type: string
                            description: "Unique identifier for the request"
                            example: "01J25YP7C2MTHAXNREE7FNPY85"
                          number:
                            type: string
                            description: "Request number"
                            example: "RE-953539"
                          volume:
                            type: string
                            description: "Volume of the request"
                            example: "250.00"
                          price:
                            type: string
                            description: "Price of the request"
                            example: "2000.00"
                          type:
                            type: string
                            enum: ["buy", "sell"]
                            description: "Type of the request (BUY or SELL)"
                            example: "BUY"
                          status:
                            type: string
                            enum:
                              ["pending", "processing", "trading", "canceled"]
                            description: "Status of the request"
                            example: "pending"
                          created_at:
                            type: string
                            format: date-time
                            description: "Creation timestamp"
                            example: "2024-07-07T06:38:04.000000Z"
                          updated_at:
                            type: string
                            format: date-time
                            description: "Last update timestamp"
                            example: "2024-07-07T06:38:04.000000Z"
                          payment_methods:
                            type: object
                            required:
                              - items
                              - pagination
                            properties:
                              items:
                                type: array
                                description: "Array of payment method items"
                                items:
                                  type: object
                                  required:
                                    - ulid
                                    - payment_method
                                  properties:
                                    ulid:
                                      type: string
                                      description: "Unique identifier for the payment method"
                                      example: "01J25YKXXAS0KX1W4383HE65GR"
                                    payment_method:
                                      type: object
                                      required:
                                        - type
                                        - holder_name
                                        - bank_name
                                        - card_number
                                        - sheba
                                        - account_no
                                        - is_active
                                        - icon
                                        - created_at
                                        - updated_at
                                      properties:
                                        type:
                                          type: string
                                          description: "Type of payment method"
                                          example: "rial_bank"
                                        holder_name:
                                          type: string
                                          description: "Name of the account holder"
                                          example: ""
                                        bank_name:
                                          type: string
                                          description: "Name of the bank"
                                          example: ""
                                        card_number:
                                          type: string
                                          description: "Card number"
                                          example: ""
                                        sheba:
                                          type: string
                                          description: "SHEBA number"
                                          example: ""
                                        account_no:
                                          type: string
                                          description: "Account number"
                                          example: ""
                                        is_active:
                                          type: boolean
                                          description: "Whether the payment method is active"
                                          example: false
                                        icon:
                                          type: string
                                          description: "payment method icon url"
                                        created_at:
                                          type: string
                                          format: date-time
                                          description: "Creation timestamp"
                                          example: "2024-07-07T06:38:04.000000Z"
                                        updated_at:
                                          type: string
                                          format: date-time
                                          description: "Last update timestamp"
                                          example: "2024-07-07T06:38:04.000000Z"
                    pagination:
                      type: object
                      required:
                        - current_page
                        - first_page_url
                        - from
                        - last_page
                        - last_page_url
                        - next_page_url
                        - path
                        - per_page
                        - prev_page_url
                        - to
                        - total
                      properties:
                        current_page:
                          type: integer
                          description: "Current page number"
                          example: 1
                        first_page_url:
                          type: string
                          description: "URL of the first page"
                          example: "http://localhost:8000/api/v1/users/requests?page=1"
                        from:
                          type: integer
                          description: "Start index of items on current page"
                          example: 1
                        last_page:
                          type: integer
                          description: "Last page number"
                          example: 1
                        last_page_url:
                          type: string
                          description: "URL of the last page"
                          example: "http://localhost:8000/api/v1/users/requests?page=1"
                        next_page_url:
                          type: string
                          nullable: true
                          description: "URL of the next page"
                          example: null
                        path:
                          type: string
                          description: "Base path for pagination URLs"
                          example: "http://localhost:8000/api/v1/users/requests"
                        per_page:
                          type: integer
                          description: "Number of items per page"
                          example: 15
                        prev_page_url:
                          type: string
                          nullable: true
                          description: "URL of the previous page"
                          example: null
                        to:
                          type: integer
                          description: "End index of items on current page"
                          example: 6
                        total:
                          type: integer
                          description: "Total number of items"
                          example: 6
