"/payment-methods":
  post:
    tags:
      - payment methods
    summary: "Create a new payment method"
    description: "This endpoint allows users to create a new payment method by providing the necessary details based on the selected payment method type (Rial bank, Foreign bank, or paypal)."
    operationId: createPaymentMethod
    parameters: []
    requestBody:
      required: true
      content:
        application/x-www-form-urlencoded:
          schema:
            type: object
            required:
              - type
              - holder_name
              - is_active
            properties:
              type:
                type: string
                description: "The type of payment method, Rial Bank: 1 | Foreign Bank:2 | Paypal: 3"
                enum:
                  - 1
                  - 2
                  - 3
                example: 1
              card_number:
                type: string
                description: "The card number (required if type is Rial Bank)"
                example: "6274129005473742"
              sheba:
                type: string
                description: "The Sheba number (required if type is Rial Bank)"
                example: "IR062960000000100324200001"
              account_no:
                type: string
                description: "The account number"
                example: "10996491"
              iban:
                type: string
                description: "The IBAN (required if type is Foreign Bank)"
                example: "DE89370400440532013000"
              bic:
                type: string
                description: "The BIC (required if type is Foreign Bank)"
                example: "DEUTDEFF"
              email:
                type: string
                format: email
                description: "The email address (required if type is Paypal)"
                example: "john.doe@example.com"
              holder_name:
                type: string
                description: "The name of the account holder"
                example: "John Doe"
              bank_name:
                type: string
                description: "The name of the bank (required if type is Rial Bank or Foreign Bank)"
                example: "Bank Melli Iran"
              is_active:
                type: integer
                enum:
                  - 0
                  - 1
                description: "Indicates if the payment method is active. Inactive: 0 | Active: 1"
                example: 1
    responses:
      '201':
        description: "Payment method created successfully"
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: "success"
                code:
                  type: integer
                  example: 201
                message:
                  type: string
                  example: "The payment method was created successfully."
                data:
                  type: object
                  properties:
                    ulid:
                      type: string
                      example: "01HZRVXSXXED0ZJ8GRMT7FXHP0"
                    holder_name:
                      type: string
                      example: "Ali Karimi"
                    bank_name:
                      type: string
                      example: "Mellat"
                    card_number:
                      type: string
                      example: "6274129005473742"
                    sheba:
                      type: string
                      example: "IR062960000000100324200001"
                    account_no:
                      type: string
                      example: "10996491"
                    is_active:
                      type: boolean
                      example: true
                    created_at:
                      type: string
                      format: date-time
                      example: "2024-06-07T08:09:31.000000Z"
                    updated_at:
                      type: string
                      format: date-time
                      example: "2024-06-07T08:09:31.000000Z"

