"/trades":
  get:
    tags:
      - trades
    summary: Retrieve trades
    description: Get a list of trades
    operationId: getAllTrades
    parameters:
      - $ref: "#/components/parameters/pageSize"
      - $ref: "#/components/parameters/pageNumber"
      - name: filter[type]
        in: query
        description: Filter trades by type (buy or sell)
        schema:
          type: string
          enum: [buy, sell]
      - name: filter[status]
        in: query
        description: Filter trades by status
        schema:
          type: string
          enum: [pending, processing, trading, canceled]
    responses:
      "200":
        description: Successful response
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Base200Response"
                - type: object
                  required:
                    - data
                  properties:
                    data:
                      type: object
                      required:
                        - items
                        - pagination
                      properties:
                        items:
                          type: array
                          items:
                            $ref: "#/components/schemas/Trade"
                        pagination:
                          $ref: "#/components/schemas/Pagination"
"/users/trades":
  get:
    tags:
      - trades
    summary: Retrieve user trades
    operationId: getUserTrades
    description: Get a list of trades for the authenticated user
    parameters:
      - name: filter[status]
        in: query
        description: Filter trades by status (active or inactive)
        schema:
          type: string
          enum: [active, inactive]
      - name: sort
        in: query
        description: Sort trades by creation date
        schema:
          type: string
          enum: [created_at, -created_at]
      - $ref: "#/components/parameters/pageSize"
      - $ref: "#/components/parameters/pageNumber"
    responses:
      "200":
        description: Successful response
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Base200Response"
                - type: object
                  required:
                    - data
                  properties:
                    data:
                      type: object
                      required:
                        - items
                        - pagination
                      properties:
                        items:
                          type: array
                          items:
                            $ref: "#/components/schemas/UserTrade"
                        pagination:
                          $ref: "#/components/schemas/Pagination"
"/users/trades/{trade}":
  get:
    tags:
      - trades
    summary: Retrieve user trade by ULID
    description: Get a trade by ULID for the authenticated user
    operationId: getUserTrade
    parameters:
      - name: trade
        in: path
        required: true
    responses:
    "200":
      description: "The deposit reason was updated successfully."
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/Base200Response"
              - type: object
                required:
                  - data
                properties:
                  data:
                    $ref: "#/components/schemas/UserTrade"

  put:
    tags:
      - trades
    summary: "update deposit reason of the trade by ULID"
    description: "This endpoint update deposit reason of the trade by ULID."
    operationId: updateDepositReason
    parameters:
      - name: trade
        in: path
        required: true
        description: "The ULID of the trade."
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - deposit_reason
            properties:
              deposit_reason:
                type: string
                description: "the reason of the deposit"
    responses:
      "200":
        description: "The deposit reason was updated successfully."
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Base200Response"
                - type: object
                  required:
                    - data
                  properties:
                    data:
                      $ref: "#/components/schemas/UserTrade"
