"/users/me":
  get:
    tags:
      - users
    summary: "Get Current User Information"
    description: "Retrieve information about the currently authenticated user."
    operationId: me
    parameters: []
    requestBody: null
    responses:
      "200":
        description: "User information retrieved successfully."
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Base200Response"
                - type: object
                  required:
                    - data
                  properties:
                    data:
                      type: object
                      required:
                        - user
                      properties:
                        user:
                          $ref: "#/components/schemas/User"
