apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-laravel
spec:
  replicas: 1
  template:
    spec:
      initContainers:
        - name: laravel-setup
          env:
            # APP--------------------------------------
            - name: APP_ENV
              value: nightly
            - name: APP_URL
              value: https://nightly.paylibero.ir

            # DB--------------------------------------
            - name: DB_HOST
              value: paylibero-db-mysql-headless
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: password

            # RECAPTCHA--------------------------------------
            - name: RECAPTCHA_V3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: secret_key
            - name: RECAPTCHA_V3_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: site_key
            - name: RECAPTCHA_V3_ENABLE
              value: "false"

            # REDIS--------------------------------------
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: redis-password

            # MAIL--------------------------------------
            - name: MAIL_USERNAME
              value: 10cSOoYX8R
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ahasend
                  key: password

            # ZIBAL_CALLBACK_URL--------------------------------------
            - name: ZIBAL_CALLBACK_URL
              value: https://nightly.paylibero.ir/api/gateway/callback

            # FINNOTECH--------------------------------------
            - name: FINNOTECH_BASE_URL
              value: https://sandboxapi.finnotech.ir
            - name: FINNOTECH_CLIENT_ID
              value: paylibero
            - name: FINNOTECH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: token
            - name: FRONTEND_URL_AFTER_PAYMENT
              value: https://nightly.paylibero.ir/dashboard/trades

            # SANCTUM--------------------------------------
            - name: SANCTUM_STATEFUL_DOMAINS
              value: localhost:4000,core-lara-33e1254e7d-paylibero-nightly.apps.ir-thr-ba1.arvancaas.ir,nightly.paylibero.ir
            - name: SESSION_DOMAIN
              value: .paylibero.ir

            # AWS--------------------------------------
            - name: AWS_URL
              value: https://files.paylibero.ir/
            - name: AWS_ENDPOINT
              value: s3.ir-thr-at1.arvanstorage.ir
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: file-storage
                  key: id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: file-storage
                  key: access-key

      containers:
        - name: core-laravel
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 200M
              memory: 1G
            requests:
              cpu: 500m
              ephemeral-storage: 200M
              memory: 1G

          env:
            # APP--------------------------------------
            - name: APP_ENV
              value: nightly
            - name: APP_URL
              value: https://nightly.paylibero.ir

            # DB--------------------------------------
            - name: DB_HOST
              value: paylibero-db-mysql-headless
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: password

            # RECAPTCHA--------------------------------------
            - name: RECAPTCHA_V3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: secret_key
            - name: RECAPTCHA_V3_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: site_key
            - name: RECAPTCHA_V3_ENABLE
              value: "false"

            # REDIS--------------------------------------
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: redis-password

            # MAIL--------------------------------------
            - name: MAIL_USERNAME
              value: 10cSOoYX8R
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ahasend
                  key: password

            # ZIBAL_CALLBACK_URL--------------------------------------
            - name: ZIBAL_CALLBACK_URL
              value: https://nightly.paylibero.ir/api/gateway/callback

            # FINNOTECH--------------------------------------
            - name: FINNOTECH_BASE_URL
              value: https://sandboxapi.finnotech.ir
            - name: FINNOTECH_CLIENT_ID
              value: paylibero
            - name: FINNOTECH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: finno-tech
                  key: token
            - name: FRONTEND_URL_AFTER_PAYMENT
              value: https://nightly.paylibero.ir/dashboard/trades

            # SANCTUM--------------------------------------
            - name: SANCTUM_STATEFUL_DOMAINS
              value: localhost:4000,core-lara-33e1254e7d-paylibero-nightly.apps.ir-thr-ba1.arvancaas.ir,nightly.paylibero.ir
            - name: SESSION_DOMAIN
              value: .paylibero.ir

            # AWS--------------------------------------
            - name: AWS_URL
              value: https://files.paylibero.ir/
            - name: AWS_BUCKET
              value: paylibero-nightly-core
            - name: AWS_USE_PATH_STYLE_ENDPOINT
              value: "true"
            - name: AWS_DEFAULT_REGION
              value: Simin
            - name: AWS_ENDPOINT
              value: s3.ir-thr-at1.arvanstorage.ir
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: file-storage
                  key: id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: file-storage
                  key: access-key
