apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-laravel
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: core-laravel
          resources:
            requests:
              memory: '128Mi'
              cpu: '64m'
            limits:
              memory: '256Mi'
              cpu: '128m'
          env:
            - name: APP_ENV
              value: nightly

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: password

            - name: RECAPTCHA_V3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: secret_key
            - name: RECAPTCHA_V3_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: google-recaptcha
                  key: site_key
            - name: RECAPTCHA_V3_ENABLE
              value: 'false'

            - name: REDIS_HOST
              value: redis-headless
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password

            - name: MAIL_MAILER
              value: mailgun
            - name: MAIL_HOST
              value: smtp.mailgun.org
            - name: MAIL_PORT
              value: '587'
            - name: MAIL_USERNAME
              value: postmaster@sandbox4a3798a69d06498199b46718ce00d304.mailgun.org
            - name: MAIL_ENCRYPTION
              value: SSL
            - name: MAIL_FROM_ADDRESS
              value: noreply@paylibero.ir
            - name: MAIL_FROM_NAME
              value: Laravel
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailgun
                  key: password
            

            
              