apiVersion: apps/v1
kind: Deployment
metadata:
  name: pex-storybook
spec:
  template:
    spec:
      containers:
        - name: pex-storybook
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '1000m'
