apiVersion: apps/v1
kind: Deployment
metadata:
  name: pex-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pex-app
          resources:
            requests:
              memory: '0.4GB'
              cpu: '64m'
            limits:
              memory: '0.8GB'
              cpu: '128m'
            env:
              - name: DEPLOYMENT_ENV
                value: nightly