apiVersion: apps/v1
kind: Deployment
metadata:
  name: pex-admin
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pex-admin
          resources:
            requests:
              memory: '128Mi'
              cpu: '64m'
            limits:
              memory: '256Mi'
              cpu: '128m'
            env:
              - name: DEPLOYMENT_ENV
                value: nightly