apiVersion: apps/v1
kind: Deployment
metadata:
  name: pex-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: pex-app
          resources:
            requests:
              memory: "256Mi"
              cpu: "128m"
            limits:
              memory: "2048Mi"
              cpu: "1024m"
            env:
              - name: DEPLOYMENT_ENV
                value: nightly