apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-worker
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: queue-worker
          resources:
            requests:
              memory: '128Mi'
              cpu: '64m'
            limits:
              memory: '256Mi'
              cpu: '128m'
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: username
           
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-laravel-mysql-db
                  key: password
            
            - name: REDIS_HOST
              value: redis-headless
            
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password