apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-worker
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: queue-worker
          resources:
            requests:
              memory: '0.4GB'
              cpu: '64m'
            limits:
              memory: '0.8GB'
              cpu: '128m'
          env:
            - name: REDIS_HOST
              value: redis-headless
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password