apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2.5
          resources:
            limits:
              cpu: 128m
              memory: 256Mi
            requests:
              cpu: 64m
              memory: 128Mi
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]  
          volumeMounts:
            - mountPath: /data
              name: redis-storage
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: redis-password
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-vol
        - name: redis-config
          configMap:
            name: redis-config